[project]
name = "hermes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb",
    "openpyxl",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langgraph",
    "openai",
    "pandas==2.3.3",
    "pypdf==6.14.0",
    "python-dotenv",
    "streamlit",
    "structlog",
]
